### ISSUE TITLE
Is it possible to create the binary once and install on multiple nodes?

### ISSUE THREAD

**Issue by michaeltlombardi** [oze4/New-PSService#2]
It'd be useful (for example, with a log archival service) to be able to write once and deploy many times with a versioned, hashed binary.

Is that currently possible? It might require a separate `New-PSService` and `Install-PSService` functionality.

**Comment by matthewoestreich** [comment]
Yes. Stop the service then copyou the .exe from the saved location to wherever you want.. Then on the new server, via cmd prompt, path to the directory where you saved the .exe. Finally, type "the_exe_name.exe /install"

Note, this will install it using the same Name, Description, etc as the source.

**Comment by michaeltlombardi** [comment]
Would it make sense to separate the two functions then (creation and installation)?
