### ISSUE TITLE
Create-NewService is a script, Uninstall-Service is a function

### ISSUE THREAD

**Issue by michaeltlombardi** [oze4/New-PSService#3]
It would be helpful if Create-NewService was rewritten as a function (and would make the overall organization more consistent). I notice it has numerous private functions internally, which shouldn't preclude it from being workd into an advanced function.

**Comment by matthewoestreich** [comment]
I provided Uninstall-Service as a value add since I figured people would be testing installing services.

**Comment by michaeltlombardi** [comment]
It's definitely an awesome value-add - but that doesn't directly bear on the initial piece (functionalizing Create-NewService) - is this because of the rejection of #1 as future work?
