### ISSUE TITLE
Create-NewPSService Requires Administrator Rights

### ISSUE THREAD

**Issue by michaeltlombardi** [oze4/New-PSService#8]
On [reddit](https://www.reddit.com/r/PowerShell/comments/59f94d/run_powershell_script_ps1_as_a_windows_service/d985x29/) it's noted that executing `Create-NewPSService` requires running from an elevated prompt.

The script doesn't appear to check for elevation nor specify it as an actual requirement. Maybe we should either add an explicit test or use `#requires` to do so?

**Comment by matthewoestreich** [comment]
In order to create a service it needs the tool you are using (whether it is this script or not) would need to be ran as Administrator.

**Comment by michaeltlombardi** [comment]
Correct, but if we inject 

``` powershell
#requires -RunAsAdministrator
```

To the script it will ensure that users are running it elevated or give a useful error if they aren't rather than letting the action fail.
