### ISSUE TITLE
Signed Binary

### ISSUE THREAD

**Issue by michaeltlombardi** [oze4/New-PSService#9]
I have no idea how hard this would be, but it'd be really interesting to be able to sign the created binary (as you might do with your script). I'm doing some basic research on this now.

**Comment by matthewoestreich** [comment]
That is a great question..  I would start with looking into signing the (source) .ps1 script you are using to "compile" to (destination) .exe.

This may help: 
Part1: https://blogs.technet.microsoft.com/heyscriptingguy/2010/06/16/hey-scripting-guy-how-can-i-sign-windows-powershell-scripts-with-an-enterprise-windows-pki-part-1-of-2/
Part2: https://blogs.technet.microsoft.com/heyscriptingguy/2010/06/17/hey-scripting-guy-how-can-i-sign-windows-powershell-scripts-with-an-enterprise-windows-pki-part-2-of-2/

**Comment by michaeltlombardi** [comment]
We should probably do that too! I did find some info on signing an exe with a code signing cert from [Microsoft](https://msdn.microsoft.com/en-us/library/windows/desktop/aa388170%28v=vs.85%29.aspx), [Digicert](https://www.digicert.com/code-signing/signcode-signtool-command-line.htm) and [David Grayson](http://www.davidegrayson.com/signing/).

Should be able to use the same code signing cert, I believe, for both.
